DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS coordinates;
DROP TABLE IF EXISTS details;

CREATE TABLE user (
  SID INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT,
  team TEXT,
  topx INTEGER,
  topy INTEGER,
  botx INTEGER,
  boty INTEGER
);